baseURL = "https://flwr.dev/"
languageCode = "en-us"
title = "FLWR.DEV"
theme = "nord"
DefaultContentLanguage = "en"

[params]
  author = "Florian Weingartshofer"
  description = "Personal Website🐧🐧"
  images = ["img/coffee.png"]
  title = "flwr.dev"

[languages]
  [languages.en]
    weight = 1


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
